version: '3.8'

services:
  wasm-builder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./pkg:/usr/share/nginx/html/pkg:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Development service for local testing
  wasm-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - ./pkg:/usr/share/nginx/html/pkg
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
    command: >
      sh -c "
        echo 'Starting development server...' &&
        nginx -g 'daemon off;'
      "
    restart: unless-stopped
